<a href="https://colab.research.google.com/github/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/blob/main/Notebooks/MVP_Machine_Learning_Previsao_Ocorrencias_Criminais-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/seguranca-publica/estatistica/dados-nacionais-1/base-de-dados-e-notas-metodologicas-dos-gestores-estaduais-sinesp-vde-2022-e-2023

In [18]:
#importação das bibliotecas necessárias ao desenvolvimento do MVP
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
#importação das bases de dados

url_2020 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2020.csv"
url_2021 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2021.csv"
url_2022 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2022.csv"
url_2023 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2023.csv"
url_2024 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2024.csv"
url_2025 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2025.csv"

df_2020 = pd.read_csv(url_2020,sep=";",low_memory=False)
df_2021 = pd.read_csv(url_2021,sep=";",low_memory=False)
df_2022 = pd.read_csv(url_2022,sep=";",low_memory=False)
df_2023 = pd.read_csv(url_2023,sep=";",low_memory=False)
df_2024 = pd.read_csv(url_2024,sep=";",low_memory=False)
df_2025 = pd.read_csv(url_2025,sep=";",low_memory=False)

In [33]:
#Criação da base de dados criminal que contém todo o conteúdo a ser utilizado no MVP
df_criminal = pd.concat([df_2020,df_2021,df_2022,df_2023,df_2024,df_2025],ignore_index=True)
df_criminal.loc[df_criminal['total_vitima']>0,['uf','municipio','evento','data_referencia','feminino','masculino','nao_informado','total_vitima']].reset_index()

,index,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima
0,8,AC,ACRELÂNDIA,Feminicídio,1/9/2020,1.0,0.0,0.0,1.0
1,15,AC,ACRELÂNDIA,Homicídio doloso,1/4/2020,0.0,1.0,0.0,1.0
2,51,AC,ACRELÂNDIA,Morte no trânsito ou em decorrência dele (exce...,1/4/2020,0.0,1.0,0.0,1.0
3,55,AC,ACRELÂNDIA,Morte no trânsito ou em decorrência dele (exce...,1/8/2020,0.0,1.0,0.0,1.0
4,57,AC,ACRELÂNDIA,Morte no trânsito ou em decorrência dele (exce...,1/10/2020,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
396657,4654932,TO,XAMBIOÁ,Mortes a esclarecer (sem indício de crime),1/10/2025,0.0,1.0,0.0,1.0
396658,4654944,TO,XAMBIOÁ,Mortes no trânsito,1/10/2025,0.0,1.0,0.0,1.0
396659,4654974,TO,XAMBIOÁ,Tentativa de feminicídio,1/4/2025,1.0,0.0,0.0,1.0
396660,4654985,TO,XAMBIOÁ,Tentativa de homicídio,1/3/2025,1.0,2.0,0.0,3.0
396661,4654990,TO,XAMBIOÁ,Tentativa de homicídio,1/8/2025,0.0,3.0,0.0,3.0

In [21]:
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4654995 entries, 0 to 4654994
Data columns (total 14 columns):
 #   Column           Dtype
---  ------           -----
 0   uf               object
 1   municipio        object
 2   evento           object
 3   data_referencia  object
 4   agente           object
 5   arma             object
 6   faixa_etaria     object
 7   feminino         float64
 8   masculino        float64
 9   nao_informado    float64
 10  total_vitima     float64
 11  total            float64
 12  total_peso       float64
 13  abrangencia      object
dtypes: float64(6), object(8)
memory usage: 497.2+ MB

In [22]:
df_criminal['data_referencia'] = pd.to_datetime(df_criminal['data_referencia'],dayfirst=True,errors='coerce')
df_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4654995 entries, 0 to 4654994
Data columns (total 14 columns):
 #   Column           Dtype
---  ------           -----
 0   uf               object
 1   municipio        object
 2   evento           object
 3   data_referencia  datetime64[ns]
 4   agente           object
 5   arma             object
 6   faixa_etaria     object
 7   feminino         float64
 8   masculino        float64
 9   nao_informado    float64
 10  total_vitima     float64
 11  total            float64
 12  total_peso       float64
 13  abrangencia      object
dtypes: datetime64[ns](1), float64(6), object(7)
memory usage: 497.2+ MB

In [23]:
idx = df_criminal.columns.get_loc('data_referencia')
df_criminal.insert(idx+1,'data_mes',df_criminal['data_referencia'].dt.month)
df_criminal.insert(idx+2,'data_ano',df_criminal['data_referencia'].dt.year)

In [24]:
df_criminal

,uf,municipio,evento,data_referencia,data_mes,data_ano,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2020-01-01,1,2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2020-02-01,2,2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2020-03-01,3,2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2020-04-01,4,2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2020-05-01,5,2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4654990,TO,XAMBIOÁ,Tentativa de homicídio,2025-08-01,8,2025,NaN,NaN,NaN,0.0,3.0,0.0,3.0,NaN,NaN,Estadual
4654991,TO,XAMBIOÁ,Tentativa de homicídio,2025-09-01,9,2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4654992,TO,XAMBIOÁ,Tentativa de homicídio,2025-10-01,10,2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4654993,TO,XAMBIOÁ,Tentativa de homicídio,2025-11-01,11,2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4654994,TO,XAMBIOÁ,Tentativa de homicídio,2025-12-01,12,2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [25]:
df_apreensao_drogas = df_criminal.loc[df_criminal['evento'].isin(['Apreensão de Cocaína','Apreensão de Maconha']),['uf','evento','data_referencia','data_ano','total_peso']].reset_index()
df_apreensao_drogas

        index  uf                evento data_referencia  data_ano  total_peso
0        1584  AC  Apreensão de Cocaína      2020-01-01      2020      17.061
1        1585  AC  Apreensão de Cocaína      2020-01-01      2020      15.041
2        1586  AC  Apreensão de Cocaína      2020-02-01      2020      13.023
3        1587  AC  Apreensão de Cocaína      2020-02-01      2020      76.627
4        1588  AC  Apreensão de Cocaína      2020-03-01      2020      15.400
...       ...  ..                   ...             ...       ...         ...
7771  4646470  TO  Apreensão de Maconha      2025-10-01      2025     102.640
7772  4646471  TO  Apreensão de Maconha      2025-11-01      2025      27.610
7773  4646472  TO  Apreensão de Maconha      2025-11-01      2025         NaN
7774  4646473  TO  Apreensão de Maconha      2025-12-01      2025       0.112
7775  4646474  TO  Apreensão de Maconha      2025-12-01      2025      19.330

[7776 rows x 6 columns]

In [26]:
df_apreensao_drogas.groupby(['uf','evento','data_ano'])['total_peso'].sum().round(2).reset_index()

     uf                evento  data_ano  total_peso
0    AC  Apreensão de Cocaína      2020     1294.50
1    AC  Apreensão de Cocaína      2021     2158.90
2    AC  Apreensão de Cocaína      2022     3398.05
3    AC  Apreensão de Cocaína      2023     1750.02
4    AC  Apreensão de Cocaína      2024      703.90
..   ..                   ...       ...         ...
319  TO  Apreensão de Maconha      2021        0.79
320  TO  Apreensão de Maconha      2022      962.47
321  TO  Apreensão de Maconha      2023      100.08
322  TO  Apreensão de Maconha      2024     1939.62
323  TO  Apreensão de Maconha      2025      386.63

[324 rows x 4 columns]

In [27]:
df_apreensao_armas = df_criminal.loc[df_criminal['evento'].isin(['Arma de Fogo Apreendida']),['uf','evento','data_referencia','data_mes','data_ano','arma','total']]
df_apreensao_armas

,uf,evento,data_referencia,data_mes,data_ano,arma,total
1632,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Metralhadora,0.0
1633,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Revolver,3.0
1634,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Outra,1.0
1635,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Carabina,0.0
1636,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Espingarda,0.0
...,...,...,...,...,...,...,...
4646686,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Pistola,0.0
4646687,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Revolver,0.0
4646688,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Rifle,0.0
4646689,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Submetralhadora,0.0
4646690,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Outra,0.0

In [28]:
df_apreensao_armas = df_apreensao_armas.loc[df_apreensao_armas['total']>0]

In [29]:
df_busca_salvamento = df_criminal.loc[df_criminal['evento'].isin(['Busca e salvamento']),['uf','evento','data_referencia','data_mes','data_ano','total']]

In [30]:
df_busca_salvamento = df_busca_salvamento.loc[df_busca_salvamento['total']>0].reset_index()