<a href="https://colab.research.google.com/github/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/blob/main/Notebooks/MVP_Machine_Learning_Previsao_Ocorrencias_Criminais-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/seguranca-publica/estatistica/dados-nacionais-1/base-de-dados-e-notas-metodologicas-dos-gestores-estaduais-sinesp-vde-2022-e-2023

In [18]:
#importação das bibliotecas necessárias ao desenvolvimento do MVP
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
#importação das bases de dados

url_2020 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2020.csv"
url_2021 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2021.csv"
url_2022 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2022.csv"
url_2023 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2023.csv"
url_2024 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2024.csv"
url_2025 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2025.csv"

df_2020 = pd.read_csv(url_2020,sep=";",low_memory=False)
df_2021 = pd.read_csv(url_2021,sep=";",low_memory=False)
df_2022 = pd.read_csv(url_2022,sep=";",low_memory=False)
df_2023 = pd.read_csv(url_2023,sep=";",low_memory=False)
df_2024 = pd.read_csv(url_2024,sep=";",low_memory=False)
df_2025 = pd.read_csv(url_2025,sep=";",low_memory=False)

In [38]:
idx = df_vitimas.columns.get_loc('data_referencia')
df_vitimas.insert(idx+1,'data_mes',df_vitimas['data_referencia'].dt.month)
df_vitimas.insert(idx+2,'data_ano',df_vitimas['data_referencia'].dt.year)

AttributeError: Can only use .dt accessor with datetimelike values

In [45]:
#Criação da base de dados que conterá todo o conteúdo a ser utilizado no MVP
df_criminal = pd.concat([df_2020,df_2021,df_2022,df_2023,df_2024,df_2025],ignore_index=True)
df_criminal['data_referencia'] = pd.to_datetime(df_criminal['data_referencia'],dayfirst=True,errors='coerce')
df_vitimas = df_criminal.loc[df_criminal['total_vitima']>0,['uf','evento','data_referencia','feminino','masculino','nao_informado','total_vitima']].reset_index()

idx = df_vitimas.columns.get_loc('data_referencia')
df_vitimas.insert(idx+1,'data_mes',df_vitimas['data_referencia'].dt.month)
df_vitimas.insert(idx+2,'data_ano',df_vitimas['data_referencia'].dt.year)

df_vitimas = df_vitimas.groupby(['uf','evento','data_referencia','data_ano','feminino','masculino','nao_informado'])['total_vitima'].sum().reset_index()

In [46]:
df_vitimas.groupby(['uf', 'evento', 'data_ano'], as_index=False).sum(numeric_only=True)

,uf,evento,data_ano,feminino,masculino,nao_informado,total_vitima
0,AC,Estupro,2020,93.0,8.0,1.0,102.0
1,AC,Estupro,2021,134.0,9.0,2.0,145.0
2,AC,Estupro,2022,257.0,16.0,24.0,297.0
3,AC,Estupro,2023,263.0,6.0,13.0,282.0
4,AC,Estupro,2024,189.0,19.0,2.0,210.0
...,...,...,...,...,...,...,...
2610,TO,Tentativa de homicídio,2021,50.0,171.0,0.0,448.0
2611,TO,Tentativa de homicídio,2022,57.0,173.0,11.0,450.0
2612,TO,Tentativa de homicídio,2023,45.0,142.0,16.0,387.0
2613,TO,Tentativa de homicídio,2024,43.0,155.0,7.0,420.0
2614,TO,Tentativa de homicídio,2025,37.0,200.0,9.0,439.0

In [27]:
df_apreensao_armas = df_criminal.loc[df_criminal['evento'].isin(['Arma de Fogo Apreendida']),['uf','evento','data_referencia','data_mes','data_ano','arma','total']]
df_apreensao_armas

,uf,evento,data_referencia,data_mes,data_ano,arma,total
1632,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Metralhadora,0.0
1633,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Revolver,3.0
1634,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Outra,1.0
1635,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Carabina,0.0
1636,AC,Arma de Fogo Apreendida,2020-01-01,1,2020,Espingarda,0.0
...,...,...,...,...,...,...,...
4646686,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Pistola,0.0
4646687,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Revolver,0.0
4646688,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Rifle,0.0
4646689,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Submetralhadora,0.0
4646690,TO,Arma de Fogo Apreendida,2025-12-01,12,2025,Outra,0.0

In [28]:
df_apreensao_armas = df_apreensao_armas.loc[df_apreensao_armas['total']>0]

In [29]:
df_busca_salvamento = df_criminal.loc[df_criminal['evento'].isin(['Busca e salvamento']),['uf','evento','data_referencia','data_mes','data_ano','total']]

In [30]:
df_busca_salvamento = df_busca_salvamento.loc[df_busca_salvamento['total']>0].reset_index()