<a href="https://colab.research.google.com/github/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/blob/main/Notebooks/MVP_Machine_Learning_Previsao_Ocorrencias_Criminais-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/seguranca-publica/estatistica/dados-nacionais-1/base-de-dados-e-notas-metodologicas-dos-gestores-estaduais-sinesp-vde-2022-e-2023

In [1]:
#importação das bibliotecas necessárias ao desenvolvimento do MVP
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#importação das bases de dados

url_2020 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2020.csv"
url_2021 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2021.csv"
url_2022 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2022.csv"
url_2023 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2023.csv"
url_2024 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2024.csv"
url_2025 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2025.csv"

df_2020 = pd.read_csv(url_2020,sep=";",low_memory=False)
df_2021 = pd.read_csv(url_2021,sep=";",low_memory=False)
df_2022 = pd.read_csv(url_2022,sep=";",low_memory=False)
df_2023 = pd.read_csv(url_2023,sep=";",low_memory=False)
df_2024 = pd.read_csv(url_2024,sep=";",low_memory=False)
df_2025 = pd.read_csv(url_2025,sep=";",low_memory=False)

In [3]:
#Criação da base de dados criminal que contém todo o conteúdo a ser utilizado no MVP
df_criminal = pd.concat([df_2020,df_2021,df_2022,df_2023,df_2024,df_2025],ignore_index=True)
df_criminal

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4654990,TO,XAMBIOÁ,Tentativa de homicídio,1/8/2025,NaN,NaN,NaN,0.0,3.0,0.0,3.0,NaN,NaN,Estadual
4654991,TO,XAMBIOÁ,Tentativa de homicídio,1/9/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4654992,TO,XAMBIOÁ,Tentativa de homicídio,1/10/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4654993,TO,XAMBIOÁ,Tentativa de homicídio,1/11/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4654994,TO,XAMBIOÁ,Tentativa de homicídio,1/12/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [5]:
df_apreensao_drogas = df_criminal.loc[df_criminal['evento'].isin(['Apreensão de Cocaína','Apreensão de Maconha']),['uf','evento','data_referencia','total_peso']].reset_index()
df_apreensao_drogas

        index  uf                evento data_referencia  total_peso
0        1584  AC  Apreensão de Cocaína        1/1/2020      17.061
1        1585  AC  Apreensão de Cocaína        1/1/2020      15.041
2        1586  AC  Apreensão de Cocaína        1/2/2020      13.023
3        1587  AC  Apreensão de Cocaína        1/2/2020      76.627
4        1588  AC  Apreensão de Cocaína        1/3/2020      15.400
...       ...  ..                   ...             ...         ...
7771  4646470  TO  Apreensão de Maconha       1/10/2025     102.640
7772  4646471  TO  Apreensão de Maconha       1/11/2025      27.610
7773  4646472  TO  Apreensão de Maconha       1/11/2025         NaN
7774  4646473  TO  Apreensão de Maconha       1/12/2025       0.112
7775  4646474  TO  Apreensão de Maconha       1/12/2025      19.330

[7776 rows x 5 columns]

In [6]:
df_apreensao_drogas.groupby(['uf','data_referencia'])['total_peso'].sum()

uf  data_referencia
AC  1/1/2020            69.008
    1/1/2021           426.492
    1/1/2022           483.136
    1/1/2023           194.596
    1/1/2024           124.902
                        ...
TO  1/9/2021             0.000
    1/9/2022             0.000
    1/9/2023             0.021
    1/9/2024           143.000
    1/9/2025            52.471
Name: total_peso, Length: 1944, dtype: float64